on:
  push: {}

jobs:
  conda-ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Docker
        run: |
          docker build -t conda -f docker/Dockerfile.conda docker/
          docker run --rm conda ldconfig --verbose
          docker run --rm -v $PWD:/code --workdir=/code -e LD_LIBRARY_PATH=/root/miniconda3/lib conda cargo test --features=dynamic-linking-from-conda
